
server:
  port: 9090

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: user-service
          uri: localhost:8081
          predicates:
            - Path=/user/**

        - id: product-service
          uri: localhost:8082
          predicates:
            - Path=/product/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

